### ISSUE TITLE
README-md

### ISSUE THREAD

**Issue by Coinhunter** [ambuc/rubber#1]
Please add a README.md and explain what it is. Rubber? wat? Rubber? Y u no documentation!?

![Image of Yaktocat](http://cdn.meme.am/instances/250x250/64287082.jpg)

**Comment by ambuc** [comment]
@Coinhunter it was gonna be a better version of http://jbuckland.com/subway/ with rubber paths between stations but i stopped midway thru collecting accurate data for whatever reason. i had it private because it was unfinished but just this week made it public and look where it got me

**Comment by Coinhunter** [comment]
Yeah would you look at that! ; )
